import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Container from "@/components/common/ui/layout/container";
import { ModalProvider } from "@/components/context/modal-context";
import Modal from "@/components/common/ui/modal/modal";
import Header from "@/components/common/ui/layout/header";
import Footer from "@/components/common/ui/layout/footer";
import { IngredientsProvider } from "@/components/context/ingredients-context";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/yakuhanjp@4.1.1/dist/css/yakuhanjp.css"
        />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Kaisei+Decol:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <IngredientsProvider>
          <ModalProvider>
            <Header />
            <Container className={"pb-15"}>{children}</Container>
            <Modal />
            <Footer />
          </ModalProvider>
        </IngredientsProvider>
      </body>
    </html>
  );
}
